input_data: "./WORK_DIR/DATA/test_clean.json"
asr_model: "./model_checkpoints/stt_en_conformer_ctc_small_ls.nemo"
spm_model_path: "./model_checkpoints/stt_en_conformer_ctc_small_ls_tokenizer.model"
DEVICE: "cuda"
TEST_BS: 1
audio_root: ""
